name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Environment configuration
        run: |
          sudo apt-get update 
          sudo apt-get install -y build-essential

      - name: Installing dependencies
        run: |
          npm install cypress --save-dev
          npm install cypress-mochawesome-reporter --save-dev 

      - name: Test execution
        run: |
          npx cypress run

          
       